### ISSUE TITLE
towards a release

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-crypto#1]
Below is a draft plan of "what we should do before an initial release". Let us please discuss if there are items missing from the list, or whether some of the items should be skipped for a release.

The set of changes we should aim for an initial release are in my opinion:
- [x] decide on the main module name (being it `Mirage_crypto` or just `Crypto`)? It'll be `Mirage_crypto`.
- [x] finish renaming of the library (best case: have nocrypto and mirage-crypto coinstallable / colinkable (requires distinct C symbols as well)
- [x] port to dune (there's earlier work, https://github.com/mirleft/ocaml-nocrypto/tree/dune is a fine start imho) see #4
- [x] get freestanding + xen support back (see https://github.com/dinosaure/ocaml-nocrypto/commits/dune and https://github.com/hannesm/ocaml-nocrypto/commits/awa-future) -- for now not using variants (i.e. stay compatible with mirage 3.7) see #4
- [x] revert the "remove sexp" commit https://github.com/mirage/mirage-crypto/commit/a58c6534c5cc5da1598f8c979ea397ea2c6b92e1 (if desired we can remove the sexp conversions at a later stage, but e.g. TLS uses them) see #4
- [x] address the various security things, see #3
- [x] setup maintainership and code review guidelines for this repository (approval is required for PRs, maintainers have write permission now, CI for linux & macOS & FreeBSD are in place)
- [x] spread into multiple packages -- the main motivation is to separate the stuff depending on the pretty big zarith / libgmp (asymmetric crypto) to allow Fortuna (the PRNG) being used by all MirageOS unikernels (see https://github.com/hannesm/ocaml-nocrypto/commits/split for an initial attempt) -- this can as well be a good preparation for reducing the overlap between crypto and digestif -- see also https://github.com/mirleft/ocaml-nocrypto/commits/breakage
- [x] ensure mirage-crypto-* works for reverse dependencies of nocrypto

at some later point, we should:
- write microbenchmarks and run with released versions (and openssl) as baseline, to evaluate potential performance regression before a release
- discuss the underlying storage data structure (atm Cstruct.t, digestif uses String/Bytes/Bigarray)
- de-duplicate the hash implementations between crypto and digestif
- define (or revise) a DH interface (so fiat and x25519 and this FFDHE can share the same module type) -- imho these libraries should be integrated into this repository as well
- define an AEAD interface (so CCM/GCM/potentially poly1305/Chacha20 can share it)
- remove the compile-time CPU feature detection (using cpuid), instead defer to runtime CPU detection (without performance regression, i.e. only do it once, not on every call to AES)

**Comment by avsm** [comment]
repository is now open so ocaml-ci should be activatable on this.

**Comment by talex5** [comment]
ocaml-ci is now enabled (doesn't work on `master` due to the old-style `opam` file name, but it's building on the `more` branch).

**Comment by hannesm** [comment]
> If we can release this first and a TLS release which ports to dune, then it will be much easier to perform the rest of the work for TLS 1.3 and digestif integration and fortuna separation asynchronously on top of those releases.

This does not match the plan I have in mind. I want to avoid yet another rebase of the TLS 1.3 branch (did that recently, it is painful). So my plan ahead is to get this package into a nice shape, then get TLS 1.3 branch merged (after further reviews and testing), and then finally use mirage-crypto in TLS and port TLS to dune. Once we're there, we can release TLS (with 1.3, mirage-crypto, and dune). :)
