### ISSUE TITLE
Roadmap for 1.0 release

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-crypto#205]
The next release will break the API, and be a 1.0. Notably:
- [x] remove P224 due to not much usage #209 
- [x] remove Hash, use digestif #213
- [x] remove sexplib0 converters from mirage-crypto-pk #208
- [x] improve performance of symmetric ciphers (AES-GCM, Chacha20-Poly1305)
   - [x] including use string in chacha/poly1305 #203 
- [x] remove usage of Cstruct.t, use string in the API
   - [x] mirage-crypto-ec moves to string #210
   - [x] mirage-crypto-pk moves to string #211
   - [x] mirage-crypto moves to string #214
   - [x] mirage-crypto-rng moves to string #212 
   - [x] use Digestif instead of Mirage_crypto.Hash #212 #215
- [x] add `encrypt_into` API to move the allocations to the call site (raising exceptions if too small buffers are passed in)
   - [x] an initial experiment #204 
   - [ ] #231 
- [x] investigate and benchmark usage of global buffers (see #186), now that bytes/string are used #219
- [x] avoid data races in des #223 #186 
- [x] (eventually) avoid mutating globals (Atomic) #221 #186 
- [x] #224
- [x] #227 
- [x] add upper bounds to existing packages requiring mirage-crypto https://github.com/ocaml/opam-repository/pull/26045 (only after this is merged, we should release)
- [x] #233 
- [x] #234 
- [x] #235

If you've further comments or are keen to retain the old API, please comment in this issue. The 0.x series will be unsupported at the point when 1.0 is released.

**Comment by hannesm** [comment]
We may want to think and address the "storing secret keys in memory (with a GC around)", as raised in https://discuss.ocaml.org/t/ann-mirage-crypto-0-11-3-with-more-speed-for-elliptic-curves-and-the-future-roadmap-of-mirage-crypto/14200/7

**Comment by Firobe** [comment]
Also, would 1.0 be the right time to discuss if we keep maintaining 32-bit support? Not to drop it for 1.0, but at least begin surveying potential users and announcing deprecation if we decide so

**Comment by hannesm** [comment]
Updated the list above. @Firobe, since you mentioned "I'd like to finish the work on NIST curves scalar multiplication for the non-base case, to improve performance a bit more for key generation in particular" <- any updates on that?

I'd target next week for a release.

**Comment by hannesm** [comment]
For the 1.0.0 release (soon), any objections to use OCaml 4.13 as lower bound? The benefit would be avoiding various local bindings. And who uses an older OCaml anyways and wants to use mirage-crypto.

Any objections @mirage/core (of course, anyone else please tell your desire).

**Comment by hannesm** [comment]
Another poll is whether we should use the Bytes/String.{get,set} functions, or go through a library (which would allow us to remove bounds checks at a global level)? In the end, my gut feeling is that we would like to have a general approach to it (related to https://discuss.ocaml.org/t/bounds-checks-for-string-and-bytes-when-retrieving-or-setting-subparts-thereof) -- but we're not there (yet?). So maybe it's fine to keep as is...

**Comment by palainp** [comment]
Thank you @hannesm for pushing that out. For the first poll, I approve the compiler upgrade (esp. it allows get/set with String and I want more / less Cstruct :) ).
As for the second poll, I don't have a strong opinion at the moment. I'm worried about the increase in the dependency cone (and the time needed to write code), but at the same time it will hopefully factor out some code and helps in performances improvements easily in other libraries.

**Comment by hannesm** [comment]
since mirage-crypto-rng already requires 4.12 (for `Atomic.`), the 4.13 bound is fine.

**Comment by hannesm** [comment]
I'll cut a release now.
