### ISSUE TITLE
security issues from nocrypto repository

### ISSUE THREAD

**Issue by hannesm** [mirage/mirage-crypto#3]
- [x] https://github.com/mirleft/ocaml-nocrypto/issues/81 (RSA-CRT) see #15
- [x] https://github.com/mirleft/ocaml-nocrypto/issues/166 (CCM mode computes incorrect tag with empty AAD), see #18
- [x] https://github.com/mirleft/ocaml-nocrypto/issues/167 (CCM mode: assertion failure when a short nonce is used), see #18
- [x] https://github.com/mirleft/ocaml-nocrypto/issues/168 (CCM mode: decrypting an empty ciphertext fails), see #18
- [x] https://github.com/mirleft/ocaml-nocrypto/issues/169 (GCM allows the empty IV, which is dangerous), see #18
- [x] use `mpz_powm_sec` instead of `mpz_powm`, see #24
- [x] constant time equality (use `eqaf`), see #15
- [x] rdrand/rdseed return value (<> 1 -> RNG not ready) and ryzen 3000 bug (always returning -1) see #17

**Comment by hannesm** [comment]
closing this issue, the leftover item is now discussed in more lenght in #24
